from __future__ import annotations

from datetime import datetime
from typing import Protocol

from loop_apidoc.core.models import (
    ApprovalDecision,
    ContractRelease,
    CurrentPointer,
    DomainEvent,
    EvidenceBundle,
    ExtractionWorkItem,
    GroundedClaim,
    RuntimeResult,
    SourceSet,
    WorkflowRecord,
)
from loop_apidoc.domain.models import GroundedApiContract
from loop_apidoc.domain.projections import Projection


class RuntimePort(Protocol):
    def propose(self, work_item: ExtractionWorkItem) -> RuntimeResult: ...


class SourcePort(Protocol):
    def acquire(self, source_set: SourceSet) -> EvidenceBundle: ...


class EvidenceStore(Protocol):
    def put_source_set(self, source_set: SourceSet) -> None: ...
    def get_source_set(self, source_set_id: str) -> SourceSet: ...
    def put_bundle(self, bundle: EvidenceBundle) -> None: ...
    def get_bundle(self, source_set_id: str) -> EvidenceBundle: ...


class ContractStore(Protocol):
    def put_workflow(self, record: WorkflowRecord) -> None: ...
    def get_workflow(self, source_set_id: str) -> WorkflowRecord: ...
    def put_runtime_result(self, source_set_id: str, result: RuntimeResult) -> None: ...
    def get_runtime_result(self, source_set_id: str) -> RuntimeResult: ...
    def put_claims(
        self, source_set_id: str, claims: tuple[GroundedClaim, ...]
    ) -> None: ...
    def get_claims(self, source_set_id: str) -> tuple[GroundedClaim, ...]: ...
    def put_contract(
        self, source_set_id: str, contract: GroundedApiContract
    ) -> None: ...
    def get_contract(self, source_set_id: str) -> GroundedApiContract: ...
    def put_projections(
        self, source_set_id: str, projections: tuple[Projection, ...]
    ) -> None: ...
    def get_projections(self, source_set_id: str) -> tuple[Projection, ...]: ...
    def put_release(self, release: ContractRelease) -> None: ...
    def get_release(self, release_id: str) -> ContractRelease: ...
    def put_current(self, pointer: CurrentPointer) -> None: ...


class ArtifactSink(Protocol):
    def publish(
        self, release_id: str, projections: tuple[Projection, ...]
    ) -> tuple[str, ...]: ...


class ApprovalPort(Protocol):
    def request(self, release: ContractRelease) -> ApprovalDecision: ...


class IdentityProvider(Protocol):
    def current_actor(self) -> str: ...


class Clock(Protocol):
    def now(self) -> datetime: ...


class EventSink(Protocol):
    def append(self, event: DomainEvent) -> None: ...
